Libraries

In [10]:
import numpy as np
import time

Basic

In [11]:
start = time.time()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])

arr3 = np.empty(len(arr1))
for i in range(len(arr1)):
    arr3[i] = arr1[i] * arr2[i]


t = time.time() - start
print(arr1)
print(arr2)
print(arr3)
print("Total Time Taken :",t)

[1 2 3 4 5]
[6 7 8 9 0]
[ 6. 14. 24. 36.  0.]
Total Time Taken : 0.00011086463928222656


Built-in

In [12]:
start = time.time()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])

arr3 = np.multiply(arr1, arr2)

t = time.time() - start
print(arr1)
print(arr2)
print(arr3)
print("Total Time Taken :",t)

[1 2 3 4 5]
[6 7 8 9 0]
[ 6 14 24 36  0]
Total Time Taken : 8.606910705566406e-05
