Libraries

In [1]:
import numpy as np
import time

Basic

In [2]:
start = time.time()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])

dot = 0
arr3 = np.empty(len(arr1))
for i in range(len(arr1)):
    arr3[i] = arr1[i] * arr2[i]

for i in range(len(arr3)):
    dot+= arr3[i]

t = time.time() - start
print(arr1)
print(arr2)
print(dot)
print("Total Time Taken :",t)

[1 2 3 4 5]
[6 7 8 9 0]
80.0
Total Time Taken : 0.00017547607421875


Built-In

In [3]:
start = time.time()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])

dot = np.dot(arr1, arr2)

t = time.time() - start
print(arr1)
print(arr2)
print(dot)
print("Total Time Taken :",t)

[1 2 3 4 5]
[6 7 8 9 0]
80
Total Time Taken : 0.00011730194091796875
